#include <iostream>

int test_date();
int test_simulation();
int test_ground_ops();
int test_ground_battle_forecast();
int test_boarding();
int test_serialization();
int test_auto_freight();
int test_freight_planner();
int test_fuel_planner();
int test_industry();
int test_refit();
int test_diplomacy();
int test_auto_routing();
int test_auto_explore();
int test_order_repeat();
int test_order_planner();
int test_determinism();
int test_event_export();
int test_content_validation();
int test_resource_catalog();
int test_materials_processing();
int test_content_overlays();
int test_content_hot_reload();
int test_spatial_index();
int test_random_scenario();
int test_file_io();
int test_autosave();
int test_json_unicode();
int test_json_bom();
int test_json_errors();
int test_json_merge_patch();
int test_json_pointer();
int test_json_pointer_autocomplete();
int test_json_pointer_glob();
int test_trace_events();
int test_state_validation();
int test_save_diff();
int test_save_delta();
int test_regression_tape();
int test_state_export();
int test_population_growth();
int test_combat_events();
int test_shields();
int test_population_transport();
int test_colonization();
int test_auto_colonize();
int test_auto_salvage();
int test_reverse_engineering();
int test_auto_tanker();
int test_ship_repairs();
int test_fleets();
int test_ai_economy();
int test_research_planner();
int test_research_schedule();
int test_colony_schedule();
int test_colony_profiles();
int test_planner_events();
int test_time_warp();
int test_contact_prediction();
int test_sensor_coverage();
int test_mineral_deposits();
int test_mobile_mining();
int test_auto_mine();
int test_power_system();
int test_digests();
int test_faction_economy_modifiers();
int test_turn_ticks();
int test_intercept();
int test_duel_simulator();
int test_duel_tournament();
int test_duel_swiss_tournament();
int test_attack_lead_pursuit();
int test_advisor();

int main() {
  int fails = 0;
  fails += test_date();
  fails += test_simulation();
  fails += test_ground_ops();
  fails += test_ground_battle_forecast();
  fails += test_boarding();
  fails += test_serialization();
  fails += test_auto_freight();
  fails += test_freight_planner();
  fails += test_fuel_planner();
  fails += test_industry();
  fails += test_refit();
  fails += test_diplomacy();
  fails += test_auto_routing();
  fails += test_auto_explore();
  fails += test_order_repeat();
  fails += test_order_planner();
  fails += test_determinism();
  fails += test_event_export();
  fails += test_content_validation();
  fails += test_resource_catalog();
  fails += test_materials_processing();
  fails += test_content_overlays();
  fails += test_content_hot_reload();
  fails += test_spatial_index();
  fails += test_random_scenario();
  fails += test_ai_economy();
  fails += test_research_planner();
  fails += test_research_schedule();
  fails += test_colony_schedule();
  fails += test_planner_events();
  fails += test_time_warp();
  fails += test_contact_prediction();
  fails += test_sensor_coverage();
  fails += test_mineral_deposits();
  fails += test_mobile_mining();
  fails += test_auto_mine();
  fails += test_power_system();
  fails += test_digests();
  fails += test_autosave();
  fails += test_file_io();
  fails += test_json_unicode();
  fails += test_json_bom();
  fails += test_json_errors();
  fails += test_json_merge_patch();
  fails += test_json_pointer();
  fails += test_json_pointer_autocomplete();
  fails += test_json_pointer_glob();
  fails += test_trace_events();
  fails += test_state_validation();
  fails += test_save_diff();
  fails += test_save_delta();
  fails += test_regression_tape();
  fails += test_state_export();
  fails += test_fleets();
  fails += test_population_growth();
  fails += test_population_transport();
  fails += test_colonization();
  fails += test_auto_colonize();
  fails += test_auto_salvage();
  fails += test_reverse_engineering();
  fails += test_auto_tanker();
  fails += test_combat_events();
  fails += test_shields();
  fails += test_turn_ticks();
  fails += test_intercept();
  fails += test_duel_simulator();
  fails += test_duel_tournament();
  fails += test_duel_swiss_tournament();
  fails += test_attack_lead_pursuit();
  fails += test_ship_repairs();
  fails += test_faction_economy_modifiers();
  fails += test_advisor();

  if (fails == 0) {
    std::cout << "All tests passed\n";
    return 0;
  }
  std::cerr << fails << " tests failed\n";
  return 1;
}
